{{- if and .Values.controller.enabled .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secrets-sync.controllerServiceAccountName" . }}
  labels:
    {{- include "secrets-sync.labels" . | nindent 4 }}
    {{- include "secrets-sync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
